### ISSUE TITLE
Don't require `width` for columns

### ISSUE THREAD

**Issue by nathanboktae** [benschulz/ko-grid#1]
Requiring width to be defined forces users of this grid to put styling concerns into the grid. Not to mention pixel-only support forces a non-responsive design.

If the grid needs to calculate a column's width, it should do so lazily.

I'm really liking the no jQuery dependency and granular plugin build-your-own grid architecture you have here over KnockoutContrib's grid, but this is a big problem.

**Comment by benschulz** [comment]
I tend to specify a small width per column so that they have good widths relative to each other and have them [scale up](http://benschulz.github.io/ko-grid-examples/examples/Column%20Scaling/resize-detection.html). However, I appreciate that that might not always yield the best possible result.

Computing column widths automatically is actually a fairly hard problem. Doing it on-the-fly is too expensive computationally. A stochastic approach will work most of the time… I suppose the approach does not matter as long as it can implemented as an extension. I'll need to think about this a bit.

**Comment by nathanboktae** [comment]
> Computing column widths automatically is actually a fairly hard problem.

I'm not asking you to do that. Let CSS and the browser do its thing and naturally layout the widths.

> Doing it on-the-fly is too expensive computationally. 

No its not, especially when you don't need to until the user has to resize a column, which you have in a plugin anyway. I'm evaluating a lot of grids and this is the only one where a width is required. I need to render arbitrary data, so this is a deal breaker to me.

**Comment by benschulz** [comment]
> I'm not asking you to do that. Let CSS and the browser do its thing and naturally layout the widths.

I'm curious, are you looking to define explicit widths for each column via css? I can definitely see that working.

However, if one or more columns are given `width: auto`, there'd be a problem. Layout-wise the grid effectively consists of three tables; header, body and the footer. The browser's layout engine would calculate their columns' widths independently.
In that scenario I don't see any reasonable way of
- getting notified whenever the browser layed out the column widths and/or
- aligning the conflicting column widths.

**Comment by nathanboktae** [comment]
> Layout-wise the grid effectively consists of three tables; header, body and the footer. 

Are these not all in the same `table` tag?

> getting notified whenever the browser layed out the column widths 

MutationObserver

**Comment by benschulz** [comment]
> Are these not all in the same table tag?

Ah, yes. If you'd be willing to give up fixed headers and footers, you could get `auto` widths in return.

The fixed headers and footers are achieved by absolutely positioning them. When I initially implemented the grid I had in fact hoped that that would enable `auto` widths. Alas, it does not. I'm not sure what the spec says, but the browsers are in agreement: absolutely positioning a `thead`/`tfoot` creates a new table flow.

> MutationObserver

To my knowledge `MutationObserver`s notify of DOM changes only, not width/layout changes.
