### ISSUE TITLE
Filtering Extension Question

### ISSUE THREAD

**Issue by cchinchilla** [benschulz/ko-grid#3]
Hello,

I was wondering if there is a way to get the set of row that are currently filtered. I haven't been able to find a way to get the filtered view of records.

Thanks

**Comment by benschulz** [comment]
Well, there are two ways of getting them. Which one applies depends on your requirements.

If you want to get a one-time stream of rows matching the filters, use `grid.source.streamValues(q => q.filteredBy(grid.predicate))`. This returns a `Promise` of a stream of values (if you _really_ need it, there's also `streamObservables` to get observables). To get at the actual values use something like `.then(vs => vs.forEach(v => console.log(v)))`.

If you want to have an actual view that will stay in sync with the filter, use `view = grid.source.openView(q => q.filteredBy(grid.predicate))`. The view needs to be disposed when you are done with it.

If you want the rows in the same order as the grid, add `.sortedBy(grid.comparator)` to the `q`uery.

Hope this helps.
